### ISSUE TITLE
`__file__` is not defined

### ISSUE THREAD

**Issue by c-bata** [c-bata/feedy#8]
```
from feedy import Feedy, logger
import os

BASE_DIR = os.path.dirname(__file__)

feedy = Feedy(os.path.join(BASE_DIR, 'feedy.dat'))


@feedy.add('http://b.hatena.ne.jp/hotentry/it.rss')
def hatena_it(feed_info, entry_info, body):
    logger.debug(entry_info['title'])


@feedy.add('http://hnrss.org/newest?points=50')
def hacker_news(feed_info, entry_info, body):
    logger.debug(entry_info['title'])

if __name__ == '__main__':
    feedy.run()
```

After that, running:

```
(myfeed) [c-bata:myfeed]$ feedy article_fetcher.py feedy -m 3 -vvv
Traceback (most recent call last):
  File "/Users/c-bata/.virtualenvs/myfeed/bin/feedy", line 11, in <module>
    sys.exit(cmd())
  File "/Users/c-bata/.virtualenvs/myfeed/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/c-bata/.virtualenvs/myfeed/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/c-bata/.virtualenvs/myfeed/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/c-bata/.virtualenvs/myfeed/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/c-bata/.virtualenvs/myfeed/lib/python3.5/site-packages/feedy.py", line 199, in cmd
    runner = _get_runner(src, obj)
  File "/Users/c-bata/.virtualenvs/myfeed/lib/python3.5/site-packages/feedy.py", line 176, in _get_runner
    exec(compile(mod.read(), src.name, 'exec'), t.__dict__)
  File "article_fetcher.py", line 4, in <module>
    BASE_DIR = os.path.dirname(__file__)
NameError: name '__file__' is not defined
```

**Comment by c-bata** [comment]
``` python
        compiled = compile(mod.read(), src.name, 'exec')
        exec(compiled, t.__dict__)
```

↓

``` python
        t.__dict__['__file__'] = src.name
        compiled = compile(mod.read(), src.name, 'exec')
        exec(compiled, t.__dict__)
```
